# AI Pipeline Manager Configuration
        
# Groq API Configuration
groq:
  api_key: 

# Stable Diffusion API Configuration
stable_diffusion:
  api_url: "https://api.stability.ai/v2beta/stable-image/generate/sd3"
  api_key: 

# General Settings
general:
  log_level: "INFO"
  max_retries: 3
  timeout: 30

# Add configurations for future tools here
# Example:
# new_tool:
#   api_key: "your_new_tool_api_key"
#   base_url: "https://api.newtool.com/v1"
